/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myself_jnitestdemo_JniUtils */

#ifndef _Included_com_myself_jnitestdemo_JniUtils
#define _Included_com_myself_jnitestdemo_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myself_jnitestdemo_JniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_myself_jnitestdemo_JniUtils_getCLanguageString
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
